### ISSUE TITLE
Dispose Pattern 리서치

### ISSUE THREAD

**Issue by ailnk0** [ailnk0/ggomi#25]
Wiki에 다음 사항 정리하기

1. Dispose Pattern이란 무엇인가
2. 장점 - 사용해야 할 때
3. 단점 - 사용하지 말아야 할 때

참고 자료 : https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose

**Comment by JPRepos** [comment]
도움이 될지 모르나 아래 링크 참조해주세요~
https://hancom.atlassian.net/wiki/spaces/DEVELOPHEAD/pages/13566758/Dispose

**Comment by ailnk0** [comment]
👍 자료 감사합니다
