### ISSUE TITLE
아이콘 리소스 추가

### ISSUE THREAD

**Issue by hyunhee2** [ailnk0/ggomi#29]
- primary 버튼 
  1. 파일 추가
  2. 변환
  3. 되돌아가기
  4. 중지
</br>

- secondary 버튼 
  1. 파일 추가
  2. 제거
  3. 설정
</br>

- 아이콘 
  1. 변환 완료
  2. 변환 실패
</br>

- expander 버튼

**Comment by ailnk0** [comment]
- primary 버튼
1. 파일 추가 : sm_r_add
2. 변환 : sm_r_run
3. 완료 : sm_r_check
4. 중지 : sm_r_stop

- secondary 버튼
1. 파일 추가 : sm_add
2. 제거 : sm_sub
3. 설정 : sm_config

- 아이콘
1. 변환 완료 : dlg_data_validate_check
2. 변환 실패 : dlg_data_validate_warning

- expander 버튼 : sm_dropdown
