### ISSUE TITLE
UI/UX 배치 재검토

### ISSUE THREAD

**Issue by JPRepos** [ailnk0/ggomi#41]

**Comment by ailnk0** [comment]
https://www.figma.com/file/t3Re0fj1XxeLmAeyZ0fD7n/PdfToOffice-(Copy)?t=vGD8fUqOz4gmMLUx-0

상기 링크에서 UI/UX 디자인 변경

1. 파일 목록 추가/제거는 좌측 상단으로 위치 이동
2. 전반적인 버튼 크기 축소
3. 버튼 색상 변경
